# based on makefile from https://spin.atomicobject.com/makefile-c-projects/
TARGET_EXEC := main

ARCH ?= $(shell arch)
BUILD_DIR := ./build-$(ARCH)
SRC_DIRS := ./src

SRCS := $(shell find $(SRC_DIRS) -name *.cpp -or -name *.c -or -name *.s)
OBJS := $(SRCS:%=$(BUILD_DIR)/%.o)
DEPS := $(OBJS:.o=.d)

include lib/pjsip/build.mak

INC_DIRS := $(shell find $(SRC_DIRS) -type d) $(BUILD_DIR)/usr/local/include
INC_FLAGS := $(addprefix -I,$(INC_DIRS))

PKG_CONFIG_SYSROOT_DIR := $(BUILD_DIR)
LDFLAGS := $(APP_LDFLAGS) $(APP_LDLIBS) -lpulse-simple -lpulse -lgpiod

CPPFLAGS ?= $(INC_FLAGS) -MMD -MP $(APP_CFLAGS)

all: $(BUILD_DIR)/$(TARGET_EXEC)

$(BUILD_DIR)/$(TARGET_EXEC): $(OBJS)
	$(CC) $(OBJS) -o $@ $(LDFLAGS)

# assembly
$(BUILD_DIR)/%.s.o: %.s
	$(MKDIR_P) $(dir $@)
	$(AS) $(ASFLAGS) -c $< -o $@

# c source
$(BUILD_DIR)/%.c.o: %.c
	$(MKDIR_P) $(dir $@)
	$(CC) $(CPPFLAGS) $(CFLAGS) -c $< -o $@

# c++ source
$(BUILD_DIR)/%.cpp.o: %.cpp
	$(MKDIR_P) $(dir $@)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $< -o $@

.PHONY: clean

clean:
	$(RM) -r $(BUILD_DIR)

-include $(DEPS)

MKDIR_P ?= mkdir -p
