//
// Created by eddie on 26/05/24.
//

#ifndef APP_DISPLAY_H
#define APP_DISPLAY_H

#ifndef APP_DISPLAY_USE_STDOUT
#define APP_DISPLAY_USE_LCD_DEVICE
#endif


#define ANSI_ESCAPE "\e"
#define ANSI_CSI    "["
#define ANSI_ESCAPE_CSI ANSI_ESCAPE ANSI_CSI
#define ANSI_ESCAPE_LCD ANSI_ESCAPE_CSI "L"

#define DISPLAY_PRINT(x)   ({fprintf(DISPLAY_OUT_STREAM, x);fflush(DISPLAY_OUT_STREAM);})
#define DISPLAY_PRINTF(x, y)   ({fprintf(DISPLAY_OUT_STREAM, x, y);fflush(DISPLAY_OUT_STREAM);})
#define DISPLAY_CLEAR() ({DISPLAY_PRINT(ANSI_ESCAPE_CSI "H" ANSI_ESCAPE_CSI "2J" DISPLAY_CLEAR_SCROLLBACK);})

#ifdef APP_DISPLAY_USE_STDOUT
// STDIO DISPLAY
#include <stdio.h>
#define DISPLAY_OUT_STREAM (stdout)
#define DISPLAY_CLEAR_SCROLLBACK ANSI_ESCAPE_CSI "3J"
#define DISPLAY_CURSOR_BLINK_OFF() ({DISPLAY_PRINT(ANSI_ESCAPE_CSI "?25l");})
#define DISPLAY_CURSOR_BLINK_ON() ({DISPLAY_PRINT(ANSI_ESCAPE_CSI "?25h");})
#define DISPLAY_GOTO_XY(x, y)   ({DISPLAY_PRINT(ANSI_ESCAPE_CSI y ";" x "H");})

#elif defined(APP_DISPLAY_USE_LCD_DEVICE)
// LCD DISPLAY
#include <stdio.h>
extern FILE* LCD_DEVICE;
#define DISPLAY_OUT_STREAM (LCD_DEVICE)
#define DISPLAY_CLEAR_SCROLLBACK // we don't have this on LCD, we can ignore
#define DISPLAY_GOTO_XY(x, y)   ({DISPLAY_PRINT(ANSI_ESCAPE_CSI "Lx" x "[y" y "];");})
#define DISPLAY_BACKLIGHT_ON() ({DISPLAY_PRINT(ANSI_ESCAPE_LCD "+");})
#define DISPLAY_BACKLIGHT_OFF() ({DISPLAY_PRINT(ANSI_ESCAPE_LCD "-");})
#define DISPLAY_ON() ({DISPLAY_PRINT(ANSI_ESCAPE_LCD "D");})
#define DISPLAY_OFF() ({DISPLAY_PRINT(ANSI_ESCAPE_LCD "d");})
#define DISPLAY_REINIT() ({DISPLAY_PRINT(ANSI_ESCAPE_LCD "I");})
#define DISPLAY_CURSOR_BLINK_OFF() ({DISPLAY_PRINT(ANSI_ESCAPE_LCD "b");})
#define DISPLAY_CURSOR_BLINK_ON() ({DISPLAY_PRINT(ANSI_ESCAPE_LCD "B");})
#else
#error "Must use either stdout or LCD as display!"
#endif

#endif //APP_DISPLAY_H
